version: "3"

networks:
  m169-project-internal:
    external: true
  m169-project-external:
    external: true

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '8080:80'
      - '8443:443'
      - '881:81'
    networks:
      - m169-project-internal
      - m169-project-external
